#!/usr/bin/env node
/**
 * Euno CLI - Command-line interface for capability management
 * Provides tools for developers to work with agent capabilities
 */

import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import axios from 'axios';
import {
  dumpEnvTemplate,
  EUNO_SERVICE_NAMES,
  EunoServiceName,
  validateManifest,
  ManifestValidationError,
} from '@euno/common';

const program = new Command();

program
  .name('euno')
  .description('Euno - Capability management CLI for AI agents')
  .version('1.0.0');

/**
 * Supported framework adapters that `euno init --framework <name>` can
 * scaffold.  Kept in sync with `packages/framework-adapters/src` —
 * adding a new framework adapter there should also add a case to
 * {@link FRAMEWORK_SCAFFOLDS} below.
 */
const SUPPORTED_FRAMEWORKS = ['langchain', 'maf', 'crewai'] as const;
type SupportedFramework = (typeof SUPPORTED_FRAMEWORKS)[number];

/**
 * Supported deployment clouds that `euno init --cloud <name>` can
 * scaffold.  Per `docs/execution-plan.md` Sprint 3 (Team DX,
 * "Cloud-Aware Scaffolding"), the CLI emits a deployment-config block
 * matching the chosen cloud's identity provider, signer, and gateway
 * fronting service.  The capability manifest itself stays
 * cloud-neutral; only the deployment block changes.
 */
const SUPPORTED_CLOUDS = ['azure', 'aws', 'gcp'] as const;
type SupportedCloud = (typeof SUPPORTED_CLOUDS)[number];

/**
 * Per-cloud deployment configuration scaffold emitted next to the
 * manifest when the caller passes `--cloud`.  The file is a
 * declarative, human-readable YAML pointing at the cloud-native
 * primitives the issuer, signer, and gateway expect, so engineers can
 * substitute their tenant-specific values without having to look up the
 * mapping themselves.  Field names match the env-var contract used by
 * the issuer (`packages/capability-issuer/src/index.ts`) and gateway
 * (`packages/tool-gateway/src/index.ts`).
 *
 * Keep in sync with the cloud-portability matrix in
 * `docs/SPRINT_5_PILOT_LAUNCH.md` § 6.
 */
const CLOUD_DEPLOYMENT_SCAFFOLDS: Record<SupportedCloud, { filename: string; contents: (agentId: string) => string }> = {
  azure: {
    filename: 'euno-deployment.azure.yaml',
    contents: (agentId) => `# Euno deployment configuration for Azure.
# Generated by \`euno init --cloud azure\` for agent "${agentId}".
#
# Replace every <PLACEHOLDER> with your tenant-specific value before
# applying.  See docs/SPRINT_5_PILOT_LAUNCH.md § 6 (cloud-portability
# matrix) and infra/bicep/main.bicep for the Bicep that provisions
# these resources end-to-end.
cloud: azure
identity:
  # IdentityAdapter implementation: 'azure-ad' (Microsoft Entra ID via
  # OIDC + Microsoft Graph).  Maps Entra group memberships into the
  # cloud-neutral UserContext consumed by the issuer policy code.
  provider: azure-ad
  tenantId: <AZURE_TENANT_ID>
  clientId: <AZURE_CLIENT_ID>
signer:
  # TokenSigner implementation: AzureSigner (HSM-backed Key Vault key,
  # Managed Identity for service auth, activity logs for key-use
  # evidence).  Matches the registered provider id in
  # packages/capability-issuer/src/default-registries.ts.
  type: azure-keyvault
  keyVaultUrl: https://<KEY_VAULT_NAME>.vault.azure.net/
  keyName: <SIGNING_KEY_NAME>
  # Either pin a specific key version, or omit to always sign with the
  # current version.
  keyVersion: <SIGNING_KEY_VERSION>
gateway:
  # Edge fronting (TLS + WAF + JWT pre-validation); the Euno tool-gateway
  # container still performs the authoritative capability check.
  edge: azure-api-management
  validateJwtPolicy: true
  # Issuer's DID Document published at /.well-known/did.json.
  issuerDid: did:web:<ISSUER_DOMAIN>
telemetry:
  logs: log-analytics
  traces: application-insights
  siem: microsoft-sentinel
distributedState:
  # Required when running > 1 gateway replica so revocation and the
  # session-scoped kill switch propagate across pods.
  redisUrl: <AZURE_CACHE_FOR_REDIS_URL>
`,
  },
  aws: {
    filename: 'euno-deployment.aws.yaml',
    contents: (agentId) => `# Euno deployment configuration for AWS.
# Generated by \`euno init --cloud aws\` for agent "${agentId}".
#
# Replace every <PLACEHOLDER> with your account-specific value before
# applying.  See docs/SPRINT_5_PILOT_LAUNCH.md § 6 (cloud-portability
# matrix) and infra/terraform/aws/main.tf for the Terraform that
# provisions these resources end-to-end.
cloud: aws
identity:
  # IdentityAdapter implementation: AWSCognitoIdentityProvider (Cognito
  # for app identities + IAM Identity Center for workforce identities).
  provider: aws-cognito
  region: <AWS_REGION>
  userPoolId: <COGNITO_USER_POOL_ID>
  clientId: <COGNITO_APP_CLIENT_ID>
signer:
  # TokenSigner implementation: AWSKMSSigner (asymmetric KMS key, IAM
  # role for service auth, CloudTrail for key-use evidence).
  type: aws-kms
  region: <AWS_REGION>
  keyId: <KMS_KEY_ID_OR_ARN>
gateway:
  # Edge fronting: API Gateway + a Lambda Authorizer for JWT
  # pre-validation; the Euno tool-gateway container still performs the
  # authoritative capability check.  See infra/aws/api-gateway/.
  edge: aws-api-gateway
  lambdaAuthorizerArn: <LAMBDA_AUTHORIZER_ARN>
  issuerDid: did:web:<ISSUER_DOMAIN>
telemetry:
  logs: cloudwatch-logs
  traces: aws-xray
  siem: security-hub
distributedState:
  # Required when running > 1 gateway replica so revocation and the
  # session-scoped kill switch propagate across pods.
  redisUrl: <ELASTICACHE_REDIS_URL>
`,
  },
  gcp: {
    filename: 'euno-deployment.gcp.yaml',
    contents: (agentId) => `# Euno deployment configuration for Google Cloud.
# Generated by \`euno init --cloud gcp\` for agent "${agentId}".
#
# Replace every <PLACEHOLDER> with your project-specific value before
# applying.  See docs/SPRINT_5_PILOT_LAUNCH.md § 6 (cloud-portability
# matrix) and infra/terraform/gcp/main.tf for the Terraform that
# provisions these resources end-to-end.
cloud: gcp
identity:
  # IdentityAdapter implementation: GCPIdentityProvider (Cloud Identity
  # / Workforce Identity Federation for human users; Workload Identity
  # Federation for service-to-service).  Matches the registered
  # provider id in packages/capability-issuer/src/default-registries.ts.
  provider: gcp-identity
  projectId: <GCP_PROJECT_ID>
  workforcePoolId: <WORKFORCE_POOL_ID>
signer:
  # TokenSigner implementation: GCPCloudKMSSigner (Cloud KMS / Cloud
  # HSM key, service account or Workload Identity Federation for service
  # auth, Cloud Audit Logs for key-use evidence).  Matches the
  # registered provider id in
  # packages/capability-issuer/src/default-registries.ts.
  type: gcp-cloudkms
  projectId: <GCP_PROJECT_ID>
  locationId: <KMS_LOCATION>
  keyRingId: <KEY_RING_ID>
  keyId: <SIGNING_KEY_ID>
  keyVersion: <SIGNING_KEY_VERSION>
gateway:
  # Edge fronting: API Gateway / Apigee / Cloud Endpoints; the Euno
  # tool-gateway container still performs the authoritative capability
  # check.  See infra/gcp/api-gateway/.
  edge: gcp-api-gateway
  issuerDid: did:web:<ISSUER_DOMAIN>
telemetry:
  logs: cloud-logging
  traces: cloud-trace
  siem: security-command-center
distributedState:
  # Required when running > 1 gateway replica so revocation and the
  # session-scoped kill switch propagate across pods.
  redisUrl: <MEMORYSTORE_REDIS_URL>
`,
  },
};

/**
 * Per-framework starter file emitted next to the YAML manifest when the
 * caller passes `--framework`.  These are intentionally minimal: a
 * compilable, self-contained starting point that wires the chosen
 * framework adapter to `@euno/agent-runtime` and points at a single
 * example tool.  Real applications should replace the placeholders.
 *
 * Keep in sync with `docs/FRAMEWORK_ADAPTERS.md`.
 */
const FRAMEWORK_SCAFFOLDS: Record<SupportedFramework, { filename: string; contents: (agentId: string) => string }> = {
  langchain: {
    filename: 'euno-langchain.ts',
    contents: (agentId) => `/**
 * Euno + LangChain wiring scaffold for agent "${agentId}".
 * Generated by \`euno init --framework langchain\`.
 *
 * See docs/FRAMEWORK_ADAPTERS.md for the design.
 */
import { createAgentRuntime } from '@euno/agent-runtime';
import {
  wrapAsLangChainTools,
  EunoLangChainCallbackHandler,
} from '@euno/framework-adapters';

export async function buildEunoLangChainTools() {
  // 1. Build the cloud-agnostic Euno runtime (identity provider + signer
  //    + gateway client are wired here; see @euno/agent-runtime docs).
  const runtime = await createAgentRuntime({
    agentId: '${agentId}',
    // ...identity / signer / gateway config goes here
  });

  // 2. Map each LangChain tool name to a (gatewayTool, gatewayResource)
  //    pair so the gateway can run the capability check.
  const tools = wrapAsLangChainTools(runtime, [
    {
      frameworkToolName: 'example_tool',
      gatewayTool: 'example_tool',
      gatewayResource: 'api://service/example',
    },
  ]);

  // 3. Hand the wrapped tools and the Euno callback handler to
  //    LangChain.  The callback handler requires a sink that receives
  //    every correlation-ID-bearing event so audit logs and traces line
  //    up.  Replace this console sink with your telemetry pipeline.
  const callbacks = [
    new EunoLangChainCallbackHandler((event) => {
      console.debug('[euno-langchain]', event);
    }),
  ];
  return { tools, callbacks, runtime };
}
`,
  },
  maf: {
    filename: 'euno-maf.ts',
    contents: (agentId) => `/**
 * Euno + Microsoft Agent Framework (MAF) wiring scaffold for agent
 * "${agentId}". Generated by \`euno init --framework maf\`.
 *
 * See docs/FRAMEWORK_ADAPTERS.md for the design.
 */
import { createAgentRuntime } from '@euno/agent-runtime';
import {
  createEunoFunctionToolMiddleware,
  createEunoAgentRunMiddleware,
} from '@euno/framework-adapters';

export async function buildEunoMafMiddleware() {
  // 1. Build the cloud-agnostic Euno runtime.
  const runtime = await createAgentRuntime({
    agentId: '${agentId}',
    // ...identity / signer / gateway config goes here
  });

  // 2. The function-tool middleware short-circuits before the model
  //    sees a denied result.  The agent-run middleware emits a
  //    structured audit event per agent run.  Note the API:
  //    \`createEunoFunctionToolMiddleware(runtime, bindings, options)\`.
  const functionToolMiddleware = createEunoFunctionToolMiddleware(
    runtime,
    [
      {
        frameworkToolName: 'example_tool',
        gatewayTool: 'example_tool',
        gatewayResource: 'api://service/example',
      },
    ],
    {
      unknownToolPolicy: 'deny',
    },
  );

  const agentRunMiddleware = createEunoAgentRunMiddleware(runtime);

  // 3. Register both middlewares on your MAF agent builder, e.g.:
  //      agent.use(functionToolMiddleware);
  //      agent.use(agentRunMiddleware);
  return { functionToolMiddleware, agentRunMiddleware, runtime };
}
`,
  },
  crewai: {
    filename: 'euno-crewai.ts',
    contents: (agentId) => `/**
 * Euno + CrewAI wiring scaffold for agent "${agentId}".
 * Generated by \`euno init --framework crewai\`.
 *
 * See docs/FRAMEWORK_ADAPTERS.md for the design.
 */
import { createAgentRuntime } from '@euno/agent-runtime';
import {
  wrapAsCrewAITools,
  EunoCrewAITaskLifecycle,
} from '@euno/framework-adapters';

export async function buildEunoCrewAITools() {
  // 1. Build the cloud-agnostic Euno runtime.
  const runtime = await createAgentRuntime({
    agentId: '${agentId}',
    // ...identity / signer / gateway config goes here
  });

  // 2. Wrap each CrewAI tool so denials fail the owning task without
  //    crashing the rest of the crew.
  const tools = wrapAsCrewAITools(runtime, [
    {
      frameworkToolName: 'example_tool',
      gatewayTool: 'example_tool',
      gatewayResource: 'api://service/example',
    },
  ]);

  // 3. The task-lifecycle hook emits a structured audit event per
  //    task and refuses to start tasks once the runtime has been
  //    terminated by the kill switch — so it requires the runtime.
  const lifecycle = new EunoCrewAITaskLifecycle(runtime);
  return { tools, lifecycle, runtime };
}
`,
  },
};

/**
 * Initialize a new agent capability manifest
 */
program
  .command('init')
  .description('Initialize a new agent capability manifest')
  .option('-a, --agent <name>', 'Agent name')
  .option('-o, --output <file>', 'Output file', './agent-capability.yaml')
  .option(
    '-f, --framework <framework>',
    `Also emit a framework-native wiring scaffold (one of: ${SUPPORTED_FRAMEWORKS.join(', ')})`,
  )
  .option(
    '-c, --cloud <cloud>',
    `Also emit a cloud-specific deployment-config scaffold (one of: ${SUPPORTED_CLOUDS.join(', ')})`,
  )
  .action((options) => {
    const agentName = options.agent || 'MyAgent';
    const outputFile = options.output;

    // Validate --framework early so the caller gets a clear error before
    // any files are written.
    let framework: SupportedFramework | undefined;
    if (options.framework !== undefined) {
      const requested = String(options.framework).toLowerCase();
      if (!(SUPPORTED_FRAMEWORKS as readonly string[]).includes(requested)) {
        console.error(
          `✗ Unsupported framework "${options.framework}". Supported: ${SUPPORTED_FRAMEWORKS.join(', ')}`,
        );
        process.exit(1);
      }
      framework = requested as SupportedFramework;
    }

    // Validate --cloud early for the same reason.  The manifest stays
    // cloud-neutral; only the deployment-config scaffold differs per
    // cloud (Sprint 3, Team DX, "Cloud-Aware Scaffolding").
    let cloud: SupportedCloud | undefined;
    if (options.cloud !== undefined) {
      const requested = String(options.cloud).toLowerCase();
      if (!(SUPPORTED_CLOUDS as readonly string[]).includes(requested)) {
        console.error(
          `✗ Unsupported cloud "${options.cloud}". Supported: ${SUPPORTED_CLOUDS.join(', ')}`,
        );
        process.exit(1);
      }
      cloud = requested as SupportedCloud;
    }

    const manifest = {
      agentId: agentName.toLowerCase().replace(/\s+/g, '-'),
      name: agentName,
      version: '1.0.0',
      requiredCapabilities: [
        {
          resource: 'api://service/endpoint',
          actions: ['read'],
          // Conditions are now a typed array (see CapabilityCondition).
          // Leave empty in the scaffold; callers add e.g.
          //   { type: 'timeWindow', notAfter: '2026-01-01T00:00:00Z' }.
          conditions: [],
        },
      ],
      optionalCapabilities: [],
      metadata: {
        description: `Capability manifest for ${agentName}`,
        owner: 'team@example.com',
        tags: [],
      },
    };

    fs.writeFileSync(outputFile, yaml.dump(manifest));
    console.log(`✓ Created capability manifest: ${outputFile}`);
    console.log(`  Agent ID: ${manifest.agentId}`);
    console.log(`  Edit the file to customize capabilities`);

    if (framework) {
      const scaffold = FRAMEWORK_SCAFFOLDS[framework];
      // Emit the framework starter alongside the manifest unless the
      // caller's --output is in a different directory; we always honour
      // the manifest's directory for the scaffold so both files stay
      // together and the caller can move them as a unit.
      const outDir = path.dirname(outputFile);
      const scaffoldPath = path.join(outDir, scaffold.filename);
      if (fs.existsSync(scaffoldPath)) {
        console.log(`  (skipping ${scaffold.filename}: file already exists)`);
      } else {
        fs.writeFileSync(scaffoldPath, scaffold.contents(manifest.agentId));
        console.log(`✓ Created ${framework} scaffold: ${scaffoldPath}`);
      }
    }

    if (cloud) {
      const deployScaffold = CLOUD_DEPLOYMENT_SCAFFOLDS[cloud];
      // Same directory rule as the framework scaffold so a caller who
      // passes both `--framework` and `--cloud` ends up with all three
      // files (manifest + framework wiring + cloud deployment) in one
      // place.
      const outDir = path.dirname(outputFile);
      const deployPath = path.join(outDir, deployScaffold.filename);
      if (fs.existsSync(deployPath)) {
        console.log(`  (skipping ${deployScaffold.filename}: file already exists)`);
      } else {
        fs.writeFileSync(deployPath, deployScaffold.contents(manifest.agentId));
        console.log(`✓ Created ${cloud} deployment scaffold: ${deployPath}`);
      }
    }
  });

/**
 * Validate a capability manifest
 */
program
  .command('validate')
  .description('Validate an agent capability manifest')
  .argument('<file>', 'Manifest file to validate')
  .action((file) => {
    try {
      const content = fs.readFileSync(file, 'utf8');
      const raw = yaml.load(content);
      const manifest = validateManifest(raw);

      console.log(`✓ Manifest is valid`);
      console.log(`  Agent: ${manifest.name} (${manifest.agentId})`);
      console.log(`  Version: ${manifest.version}`);
      console.log(`  Required capabilities: ${manifest.requiredCapabilities.length}`);
    } catch (error) {
      if (error instanceof ManifestValidationError) {
        console.error(`✗ Validation failed: ${error.message}`);
      } else {
        console.error(`✗ Validation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
      process.exit(1);
    }
  });

/**
 * Request a capability token
 */
program
  .command('request')
  .description('Request a capability token from the issuer')
  .option('-i, --issuer <url>', 'Issuer URL', process.env.EUNO_ISSUER_URL || 'http://localhost:3001')
  .option('-a, --agent <id>', 'Agent ID (required)', '')
  .option('-t, --token <token>', 'Azure AD bearer token (or set AZURE_AD_TOKEN env var)', process.env.AZURE_AD_TOKEN || '')
  .option('-m, --manifest <file>', 'Capability manifest file')
  .option('-r, --resources <resources...>', 'Resource URIs (e.g., api://service/endpoint)')
  .option('--actions <actions...>', 'Actions (e.g., read write)')
  .action(async (options) => {
    // Also accept token from env var directly (options default already handles this,
    // but guard here in case both paths yield an empty string)
    const token: string = options.token;
    if (!token) {
      console.error('✗ Azure AD bearer token is required');
      console.error('  Use --token <token> or set the AZURE_AD_TOKEN environment variable');
      console.error('  Example: euno request --agent my-agent --token $AZURE_AD_TOKEN');
      process.exit(1);
    }

    if (!options.agent) {
      console.error('✗ Agent ID is required (use --agent)');
      process.exit(1);
    }

    console.log(`Requesting capability from ${options.issuer}...`);
    console.log(`  Agent ID: ${options.agent}`);

    try {
      let requestedCapabilities: Array<{resource: string; actions: string[]}> = [];

      // If manifest file provided, load capabilities from it
      if (options.manifest) {
        const content = fs.readFileSync(options.manifest, 'utf8');
        const manifest = yaml.load(content) as Record<string, unknown>;

        if (!Array.isArray(manifest.requiredCapabilities) || manifest.requiredCapabilities.length === 0) {
          console.error('✗ Manifest must contain a non-empty "requiredCapabilities" array');
          process.exit(1);
        }

        const invalid = (manifest.requiredCapabilities as unknown[]).findIndex(
          (cap) =>
            typeof (cap as Record<string, unknown>).resource !== 'string' ||
            !Array.isArray((cap as Record<string, unknown>).actions)
        );
        if (invalid !== -1) {
          console.error(`✗ requiredCapabilities[${invalid}] must have a "resource" string and an "actions" array`);
          process.exit(1);
        }

        requestedCapabilities = manifest.requiredCapabilities as Array<{resource: string; actions: string[]}>;
        console.log(`  Loaded ${requestedCapabilities.length} capabilities from manifest`);
      }
      // Otherwise use command-line resources and actions (both flags required together)
      else if (options.resources && options.actions) {
        requestedCapabilities = options.resources.map((resource: string) => ({
          resource,
          actions: options.actions,
        }));
      } else if (options.resources || options.actions) {
        console.error('✗ --resources and --actions must be provided together');
        console.error('  Example: euno request --agent my-agent --resources api://svc/data --actions read write');
        process.exit(1);
      }
      // Default fallback
      else {
        requestedCapabilities = [{
          resource: 'api://service/endpoint',
          actions: ['read'],
        }];
        console.log('  Using default capabilities (no manifest or resources specified)');
      }

      const response = await axios.post(
        `${options.issuer}/api/v1/issue`,
        {
          agentId: options.agent,
          requestedCapabilities,
        },
        {
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          timeout: 10000,
        }
      );

      console.log('\n✓ Successfully issued capability token:');
      console.log(`  Token ID: ${response.data.tokenId}`);
      console.log(`  Expires: ${new Date(response.data.expiresAt * 1000).toISOString()}`);
      console.log(`  Capabilities: ${response.data.capabilities.length}`);
      console.log('\nToken (save this):');
      console.log(response.data.token);
    } catch (error) {
      if (axios.isAxiosError(error)) {
        console.error('\n✗ Request failed:');
        console.error(`  Status: ${error.response?.status || 'N/A'}`);
        console.error(`  Message: ${error.response?.data?.message || error.message}`);
        if (error.response?.data?.code) {
          console.error(`  Code: ${error.response.data.code}`);
        }
      } else {
        console.error(`✗ Unexpected error: ${error instanceof Error ? error.message : 'Unknown error'}`);
      }
      process.exit(1);
    }
  });

/**
 * Configuration commands.
 *
 * `euno config` (no subcommand) preserves the long-standing UX of
 * printing the CLI's current environment variables. The new
 * `dump-template` subcommand emits a `.env.example` for one of the
 * services from the typed `EunoConfig` Zod schema in
 * `@euno/common` — see R-5 in
 * `docs/IMPROVEMENTS_AND_REFACTORING.md`.
 */
const configCmd = program
  .command('config')
  .description('Show CLI configuration or generate service `.env.example` files');

configCmd
  .command('show', { isDefault: true })
  .description('Show current CLI configuration')
  .action(() => {
    console.log('Euno CLI Configuration:');
    console.log(`  Default issuer: http://localhost:3001`);
    console.log(`  Default gateway: http://localhost:3002`);
    console.log('');
    console.log('Environment variables:');
    console.log(`  EUNO_ISSUER_URL: ${process.env.EUNO_ISSUER_URL || '(not set)'}`);
    console.log(`  EUNO_GATEWAY_URL: ${process.env.EUNO_GATEWAY_URL || '(not set)'}`);
  });

configCmd
  .command('dump-template')
  .description(
    'Print a `.env.example` for the named service, generated from the EunoConfig Zod schema in @euno/common. The output is the canonical replacement for the per-service hand-curated .env.example / .env.template files.',
  )
  .requiredOption(
    '-s, --service <name>',
    `Service name (one of: ${EUNO_SERVICE_NAMES.join(', ')})`,
  )
  .action((opts: { service: string }) => {
    const service = opts.service as EunoServiceName;
    if (!(EUNO_SERVICE_NAMES as readonly string[]).includes(service)) {
      console.error(
        `✗ Unknown service "${opts.service}". Expected one of: ${EUNO_SERVICE_NAMES.join(', ')}`,
      );
      process.exit(1);
    }
    process.stdout.write(dumpEnvTemplate(service));
  });

/**
 * Schema version management commands
 * Check and plan token schema version migrations
 */
const versionCmd = program
  .command('schema-version')
  .description('Manage and migrate capability token schema versions');

versionCmd
  .command('check')
  .description('Check supported schema versions on a capability issuer')
  .option('-i, --issuer <url>', 'Issuer URL', process.env.EUNO_ISSUER_URL || 'http://localhost:3001')
  .action(async (options) => {
    try {
      const url = `${options.issuer}/.well-known/capability-issuer`;
      const response = await axios.get(url, { timeout: 10000 });
      const meta = response.data;

      console.log(`Capability issuer: ${meta.issuer}`);
      console.log(`Current token schema version: ${meta.schemaVersions?.current ?? '(unknown)'}`);
      console.log(`Supported schema versions:    ${(meta.schemaVersions?.supported ?? []).join(', ')}`);
      console.log(`Signing algorithms:           ${(meta.signingAlgorithms ?? []).join(', ')}`);
    } catch (error) {
      if (axios.isAxiosError(error)) {
        console.error(`✗ Could not reach issuer at ${options.issuer}`);
        console.error(`  ${error.message}`);
      } else {
        console.error(`✗ Unexpected error: ${error instanceof Error ? error.message : String(error)}`);
      }
      process.exit(1);
    }
  });

versionCmd
  .command('plan')
  .description('Generate a step-by-step migration plan for a schema version upgrade')
  .argument('<from>', 'Current schema version (e.g. 1.0)')
  .argument('<to>', 'Target schema version (e.g. 1.1)')
  .option('--json', 'Output plan as JSON')
  .action((from: string, to: string, options) => {
    const fromParts = from.split('.').map(Number);
    const toParts = to.split('.').map(Number);
    const fromMajor = fromParts[0] ?? NaN;
    const fromMinor = fromParts[1] ?? NaN;
    const toMajor = toParts[0] ?? NaN;
    const toMinor = toParts[1] ?? NaN;

    if (isNaN(fromMajor) || isNaN(fromMinor) || isNaN(toMajor) || isNaN(toMinor)) {
      console.error('✗ Versions must be in MAJOR.MINOR format (e.g. 1.0, 1.1, 2.0)');
      process.exit(1);
    }

    const isMajor = toMajor > fromMajor;
    const isDowngrade = toMajor < fromMajor || (toMajor === fromMajor && toMinor < fromMinor);

    if (isDowngrade) {
      console.error('✗ Downgrade migrations are not supported.');
      process.exit(1);
    }

    const plan = {
      from,
      to,
      type: isMajor ? 'major' : 'minor',
      steps: isMajor
        ? [
            { phase: 'Preparation (Week 1–4)', action: `Add "${to}" to SUPPORTED_SCHEMA_VERSIONS in gateway` },
            { phase: 'Preparation (Week 1–4)', action: 'Implement version-specific parsing/validation logic for new schema shape' },
            { phase: 'Preparation (Week 1–4)', action: 'Deploy gateway updates and verify 100% rollout before proceeding' },
            { phase: 'Transition (Week 5–8)', action: `Update CAPABILITY_TOKEN_SCHEMA_VERSION to "${to}" in issuer` },
            { phase: 'Transition (Week 5–8)', action: 'Deploy issuer updates; both versions coexist during token TTL window' },
            { phase: 'Validation (Week 9–12)', action: `Monitor token version distribution; ensure no "${from}" tokens remain (check TTL)` },
            { phase: 'Deprecation (Week 13+)', action: `Remove "${from}" from SUPPORTED_SCHEMA_VERSIONS in gateway` },
            { phase: 'Deprecation (Week 13+)', action: 'Deploy gateway updates and update documentation' },
          ]
        : [
            { phase: 'Step 1', action: `Add "${to}" to SUPPORTED_SCHEMA_VERSIONS in gateway (packages/common/src/types.ts)` },
            { phase: 'Step 1', action: 'Deploy gateway updates and verify rollout' },
            { phase: 'Step 2', action: `Update CAPABILITY_TOKEN_SCHEMA_VERSION to "${to}" in issuer (packages/common/src/types.ts)` },
            { phase: 'Step 2', action: 'Deploy issuer updates; monitor token version distribution' },
            { phase: 'Step 3 (optional)', action: `After migration window, remove "${from}" from SUPPORTED_SCHEMA_VERSIONS` },
          ],
      warnings: isMajor
        ? [
            'NEVER deploy issuer before all gateways are updated',
            'Old gateways will reject tokens with the new major version',
            `Cross-version delegation is blocked: cannot attenuate a "${from}" token into a "${to}" token`,
          ]
        : [
            'NEVER deploy issuer before all gateways are updated',
            `Gateways only accept versions explicitly listed in SUPPORTED_SCHEMA_VERSIONS — an unupdated gateway will reject "${to}" tokens`,
          ],
    };

    if (options.json) {
      console.log(JSON.stringify(plan, null, 2));
    } else {
      console.log(`\nMigration plan: ${from} → ${to} (${plan.type} version bump)\n`);
      let lastPhase = '';
      for (const step of plan.steps) {
        if (step.phase !== lastPhase) {
          console.log(`\n  ${step.phase}:`);
          lastPhase = step.phase;
        }
        console.log(`    • ${step.action}`);
      }
      console.log('\n  ⚠  Warnings:');
      for (const w of plan.warnings) {
        console.log(`    • ${w}`);
      }
      console.log('');
    }
  });

versionCmd
  .command('validate-token')
  .description('Decode and validate the schema version of a capability token')
  .argument('<token>', 'JWT capability token to inspect')
  .option(
    '--against-jwks <url>',
    'Fetch the JWKS from <url> and verify the token signature. ' +
    'Reports the key ID used and whether the signature is valid. ' +
    'Does NOT check expiry or audience — use for offline issuer verification.',
  )
  .action(async (token: string, options: { againstJwks?: string }) => {
    try {
      // Decode without verification (inspection only)
      const parts = token.split('.');
      if (parts.length !== 3) {
        console.error('✗ Not a valid JWT (expected 3 parts separated by ".")');
        process.exit(1);
      }
      // parts[1] is always defined when parts.length === 3; guard against empty string
      const payloadPart = parts[1];
      if (!payloadPart) {
        console.error('✗ Not a valid JWT (empty payload segment)');
        process.exit(1);
      }
      const payload = JSON.parse(Buffer.from(payloadPart, 'base64url').toString('utf8'));
      const schemaVersion: unknown = payload.schemaVersion;

      if (!schemaVersion) {
        console.error('✗ Token is missing the required schemaVersion field');
        process.exit(1);
      }
      if (typeof schemaVersion !== 'string') {
        console.error(`✗ schemaVersion must be a string, got: ${typeof schemaVersion}`);
        process.exit(1);
      }

      console.log(`Token schema version: ${schemaVersion}`);
      console.log(`Issuer:  ${payload.iss ?? '(none)'}`);
      console.log(`Subject: ${payload.sub ?? '(none)'}`);
      console.log(`Expires: ${payload.exp ? new Date(payload.exp * 1000).toISOString() : '(none)'}`);

      // If --against-jwks is supplied, verify the token's signature.
      if (options.againstJwks) {
        const jwksUrl = options.againstJwks;
        // Decode the header to surface the kid.
        const headerPart = parts[0];
        let kid: string | undefined;
        try {
          const header = JSON.parse(Buffer.from(headerPart!, 'base64url').toString('utf8'));
          kid = typeof header.kid === 'string' ? header.kid : undefined;
        } catch {
          // header decode failure is non-fatal for the JWKS check
        }
        console.log(`\nVerifying signature against JWKS: ${jwksUrl}`);
        if (kid) {
          console.log(`Key ID (kid): ${kid}`);
        } else {
          console.log('Key ID (kid): (none in token header)');
        }

        try {
          // Dynamic import keeps the CLI startup fast when --against-jwks
          // is not used, and avoids bundling jose into the base command.
          const { createRemoteJWKSet, jwtVerify } = await import('jose');
          const JWKS = createRemoteJWKSet(new URL(jwksUrl));
          // We only verify the signature here — the caller is responsible
          // for interpreting expiry / audience claims for their use-case.
          // Pass clockTolerance=Infinity and skip audience check so this
          // works on already-expired tokens during incident review.
          await jwtVerify(token, JWKS, {
            clockTolerance: Infinity,
            // Skip audience: this is an offline inspection tool.
          });
          console.log('✓ Signature is VALID — token was signed by a key in the JWKS');
        } catch (verifyError) {
          console.error(
            `✗ Signature verification FAILED: ${verifyError instanceof Error ? verifyError.message : String(verifyError)}`,
          );
          process.exit(1);
        }
      }
    } catch (error) {
      console.error(`✗ Failed to decode token: ${error instanceof Error ? error.message : String(error)}`);
      process.exit(1);
    }
  });

program.parse(process.argv);

// Show help if no command specified
if (!process.argv.slice(2).length) {
  program.outputHelp();
}
