{{/*
capability-issuer Deployment
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "euno.fullname" . }}-issuer
  labels:
    {{- include "euno.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer
spec:
  replicas: {{ .Values.issuer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: euno-issuer
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: euno-issuer
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: issuer
    spec:
      containers:
        - name: issuer
          image: "{{ .Values.issuer.image.repository }}:{{ .Values.issuer.image.tag }}"
          imagePullPolicy: {{ .Values.issuer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.issuer.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ include "euno.fullname" . }}-issuer-config
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "euno.fullname" . }}-issuer
  labels:
    {{- include "euno.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer
spec:
  type: {{ .Values.issuer.service.type }}
  ports:
    - name: http
      port: {{ .Values.issuer.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: euno-issuer
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "euno.fullname" . }}-issuer-config
  labels:
    {{- include "euno.labels" . | nindent 4 }}
    app.kubernetes.io/component: issuer
data:
  {{- range $key, $val := .Values.issuer.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
