module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  testMatch: ['**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js'],
  transform: {
    '^.+\\.ts$': ['ts-jest', {
      tsconfig: {
        paths: {
          '@euno/common-core': ['../../../public/packages/common/src'],
          '@euno/common-core/runtime': ['../../../public/packages/common/src/runtime'],
          '@euno/common-infra': ['../common-infra/src'],
          '@euno/common': ['../common/src'],
          '@euno/common/wire': ['../common/src/wire'],
          '@euno/common/runtime': ['../common/src/runtime'],
          '@euno/capability-issuer': ['../capability-issuer/src'],
          '@euno/capability-issuer/adapters': ['../capability-issuer/src/exports'],
          '@euno/tool-gateway': ['../tool-gateway/src'],
          '@euno/agent-runtime': ['../agent-runtime/src'],
          '@euno/partner-issuer-sim': ['../partner-issuer-sim/src'],
          '@euno/db-token-service': ['../db-token-service/src'],
          '@euno/storage-grant-service': ['../storage-grant-service/src'],
          '@euno/mcp': ['../../../public/packages/mcp/src'],
          '@modelcontextprotocol/sdk/types.js': ['../../../node_modules/@modelcontextprotocol/sdk/dist/cjs/types.d.ts'],
        },
      },
    }],
  },
  moduleNameMapper: {
    '^@euno/common-core$': '<rootDir>/../../../public/packages/common/src',
    '^@euno/common-core/runtime$': '<rootDir>/../../../public/packages/common/src/runtime',
    '^@euno/common-infra$': '<rootDir>/../common-infra/src',
    '^@euno/common$': '<rootDir>/../common/src',
    '^@euno/common/wire$': '<rootDir>/../common/src/wire',
    '^@euno/common/runtime$': '<rootDir>/../common/src/runtime',
    '^@euno/capability-issuer$': '<rootDir>/../capability-issuer/src',
    '^@euno/capability-issuer/adapters$': '<rootDir>/../capability-issuer/src/exports',
    '^@euno/tool-gateway$': '<rootDir>/../tool-gateway/src',
    '^@euno/agent-runtime$': '<rootDir>/../agent-runtime/src',
    '^@euno/partner-issuer-sim$': '<rootDir>/../partner-issuer-sim/src',
    '^@euno/db-token-service$': '<rootDir>/../db-token-service/src',
    '^@euno/storage-grant-service$': '<rootDir>/../storage-grant-service/src',
    '^@euno/mcp$': '<rootDir>/../../../public/packages/mcp/src',
    '^@modelcontextprotocol/sdk/(.+\\.js)$': '<rootDir>/../../../node_modules/@modelcontextprotocol/sdk/dist/cjs/$1',
  },
  testTimeout: 30000,
  verbose: true,
};
